#config/default.toml

[node_settings]
version = 2
node_ip = "127.0.0.1"
port = 9005
unit_address = "1234"
priority = 1
codec = 1
keep_alive_interval = 10

[logging]
directory = "logs"
file_name = "dip_client.log"
rotation = "daily"
retention_hours = 24
level = "debug"